// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * One sidebar per section of the site, each opened from its own navbar item.
 * Inside a section the order comes from the folders: `_category_.json`
 * files and `sidebar_position` in the front matter of the pages.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Current lecture series (docs/wyklady-bezp)
  wykladySidebar: [
    {
      type: 'category',
      label: 'Wykłady',
      link: {
        type: 'generated-index',
        slug: '/wyklady-bezp',
        title: 'Wykłady',
        description:
          'Wykłady z bezpieczeństwa systemów monitorowania instalacji OZE - 10 wykładów, 20 godzin',
      },
      collapsible: false,
      items: ['intro', {type: 'autogenerated', dirName: 'wyklady-bezp'}],
    },
  ],

  // Exercises (docs/cwiczenia), opens on cwiczenia/index.md
  cwiczeniaSidebar: [{type: 'autogenerated', dirName: 'cwiczenia'}],

  // Earlier lecture series on monitoring (docs/wyklady), to be removed later
  archiwumSidebar: [
    {
      type: 'category',
      label: 'Wykłady: monitoring (archiwum)',
      link: {
        type: 'generated-index',
        slug: '/wyklady',
        title: 'Wykłady: monitoring (archiwum)',
        description:
          'Poprzednia seria wykładów o systemach monitorowania instalacji OZE',
      },
      collapsible: false,
      items: [{type: 'autogenerated', dirName: 'wyklady'}],
    },
  ],
};

export default sidebars;
