// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * One sidebar per section of the site, each opened from its own navbar item.
 * Inside a section the order comes from the folders: `_category_.json`
 * files and `sidebar_position` in the front matter of the pages.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Lecture series (docs/wyklady-bezp); the 2025/26 lectures are archived in archiwum/2025-26/
  wykladySidebar: [
    {
      type: 'category',
      label: 'Wykłady',
      link: {
        type: 'generated-index',
        slug: '/wyklady-bezp',
        title: 'Wykłady',
        description:
          'Wykłady z systemów bezpieczeństwa i monitorowania instalacji OZE: 10 wykładów po 90 minut (w opracowaniu, rok 2026/27)',
      },
      collapsible: false,
      items: ['intro', {type: 'autogenerated', dirName: 'wyklady-bezp'}],
    },
  ],

  // Exercises (docs/cwiczenia), opens on cwiczenia/index.md
  cwiczeniaSidebar: [{type: 'autogenerated', dirName: 'cwiczenia'}],
};

export default sidebars;
