#!/usr/bin/env python3
"""Collect every bibliography entry of all lectures into one markdown list (sources-used.md).

Usage: python3 collect_sources.py [docs_root] > _lecture-kit/sources-used.md
  docs_root  folder with the lecture folders (default /home/claude/repo/bezp-monit/docs/wyklady-bezp)

Reads the '## Źródła' list at the end of every topic page. One row per URL: the reference text as first
written, and the lectures/pages that cite it. Later lectures reuse the same URL for the same source.
"""
import glob
import os
import re
import sys
from datetime import date

root = sys.argv[1] if len(sys.argv) > 1 else "/home/claude/repo/bezp-monit/docs/wyklady-bezp"
url_re = re.compile(r"https?://[^\s\)\]>]+")
entries = {}  # url -> {"ref": str, "where": [..]}

for page in sorted(glob.glob(os.path.join(root, "wyklad-*", "*.md*"))):
    lecture = os.path.basename(os.path.dirname(page))
    num = re.match(r"wyklad-(\d\d)", lecture)
    tag = f"W{int(num.group(1))}" if num else lecture
    src = open(page, encoding="utf-8").read()
    tail = src.split("</SlideContainer>")[-1]
    m = re.search(r"\n## Źródła\n([\s\S]*)", tail)
    if not m:
        continue
    for line in m.group(1).splitlines():
        if not re.match(r"^\s*(\d+\.|-)\s+", line):
            continue
        ref = re.sub(r"^\s*(\d+\.|-)\s+", "", line).strip()
        for u in url_re.findall(ref):
            u = u.rstrip(".,;")
            e = entries.setdefault(u, {"ref": ref, "where": []})
            w = f"{tag} {os.path.basename(page)}"
            if w not in e["where"]:
                e["where"].append(w)

print("# Sources already cited in the lectures")
print()
print(f"Generated by `tools/collect_sources.py` on {date.today():%d.%m.%Y} from the `## Źródła` lists. "
      "Do not edit by hand; regenerate after each lecture. Reuse the same URL for the same source.")
print()
print(f"{len(entries)} distinct URLs.")
print()
print("| Reference (as first cited) | Cited in |")
print("|---|---|")
for u, e in sorted(entries.items(), key=lambda kv: kv[1]["ref"].lower()):
    ref = e["ref"].replace("|", "\\|")
    where = "; ".join(e["where"])
    print(f"| {ref} | {where} |")
