# Accepted fixes for W3 (30.09.2026). Each entry: (id, file, source/severity, note, old, new, count)
# count = expected number of occurrences of `old` (all are replaced).
L = "/mnt/user-data/outputs/lecture/wyklad-03-architektura-monitoringu/"
P25 = "https://www.nerc.com/globalassets/standards/reliability-standards/prc/prc-002-5.pdf"
P23 = "https://www.nerc.com/globalassets/standards/projects/2015-09/prc-002-3---clean.pdf"
P28 = "https://www.nerc.com/globalassets/standards/reliability-standards/prc/prc-028-1.pdf"
F01 = "01-cele-architektura-i-czas.mdx"
F02 = "02-tor-pomiarowy.mdx"
F03 = "03-niepewnosc-i-wzorcowanie.mdx"
F04 = "04-czujniki-i-monitoring-pv.mdx"
F05 = "05-uszkodzenia-toru-i-przyklad-biogazowy.mdx"
F06 = "06-podsumowanie.mdx"
FIX = "index.md"
ENAC = "https://www.enac.es/documents/7020/635abf3f-262a-4b3b-952f-10336cdfae9e"
EA = "https://european-accreditation.org/wp-content/uploads/2018/10/EA-4-02.pdf"
FNR = "https://www.fnr.de/fileadmin/Projekte/2023/Mediathek/Broschuere_Basisdaten_Bioenergie_2023_web.pdf"
T13 = "https://iea-pvps.org/wp-content/uploads/2020/01/IEA-PVPS_T13-D2_3_Analytical_Monitoring_of_PV_Systems_Final.pdf"

FIXES = [
# ---------------- 01 ----------------
("1", F01, "F1 major (coordinator opened PRC-002-5)",
 "the cited PRC-002-3 URL is Draft 1 (2018); current version PRC-002-5 (Board 8.10.2024, FERC 20.02.2025), R10 unchanged",
 "standardy NERC (Ameryka Północna) PRC-002-3 (wymaganie R10) i PRC-028-1 (R6)",
 "standardy NERC (Ameryka Północna) PRC-002-5 (wymaganie R10) i PRC-028-1 (R6)", 1),
("2", F01, "F1 major (consequence)",
 "source lines on the UTC and synchronisation slides point to the current PRC-002-5",
 f"[NERC, PRC-002-3]({P23}); [NERC, PRC-028-1]({P28})",
 f"[NERC, PRC-002-5]({P25}); [NERC, PRC-028-1]({P28})", 2),
("3", F01, "F1 major (consequence)",
 "PRC-002-5 and PRC-028-1 were adopted and approved on the same dates",
 "PRC-002-3 (R10) — zegary rejestracji sekwencji zdarzeń i zakłóceń w granicach ±2 ms od UTC; PRC-028-1 dla źródeł przyłączonych przez falowniki (przyjęty przez zarząd NERC 8.10.2024, zatwierdzony przez FERC, federalnego regulatora energetyki USA, 20.02.2025) — ±100 ms dla danych z poziomu falownika i ±1 ms dla pozostałych urządzeń.",
 "PRC-002-5 (R10) — zegary rejestracji sekwencji zdarzeń i zakłóceń w granicach ±2 ms od UTC; PRC-028-1 dla źródeł przyłączonych przez falowniki — ±100 ms dla danych z poziomu falownika i ±1 ms dla pozostałych urządzeń. Oba standardy przyjął zarząd NERC 8.10.2024, a FERC, federalny regulator energetyki USA, zatwierdził je 20.02.2025.", 1),
("4", F01, "F1 major (coordinator opened the manuscript)",
 "Macii & Rinaldi, Table 1 caption: classes 'specified in the IEC Standard 61850-5:2013'",
 "- Macii i Rinaldi dzielą wymagania na klasy od 1 µs (pomiary fazorów) przez 1 ms (znakowanie szybkich zdarzeń) do ponad 1 s; to klasyfikacja autorów, a nie oznaczenia IEC 61850-5.",
 "- Macii i Rinaldi, powołując się na IEC 61850-5:2013, podają sześć klas dokładności synchronizacji: od 1 µs (pomiary fazorów) przez 1 ms (znakowanie szybkich zdarzeń) do ponad 1 s (tekstu normy nie sprawdzaliśmy).", 1),
("5", F01, "F1 minor",
 "RFC 5905 speaks of precision ('precise within'), not accuracy",
 "RFC 5905: od kilkudziesięciu µs (serwery pierwotne) do kilkudziesięciu ms (interwał odpytywania do 36 h)",
 "RFC 5905 podaje precyzję (ang. precise within) od kilkudziesięciu µs (serwery pierwotne) do kilkudziesięciu ms (interwał odpytywania do 36 h)", 1),
("6", F01, "F1 major (consequence) + F1 minor #3",
 "Interim Report sentence is quoted in the guidelines of the PRC-002-3 draft; ±2 ms already in PRC-002-2; current PRC-002-5",
 "cytowany w uzasadnieniu standardu NERC PRC-002-3:",
 "cytowany w wytycznych do projektu standardu NERC PRC-002-3 (2018):", 1),
("7", F01, "F1 minor #3",
 "±2 ms (R10) was already in PRC-002-2; current version PRC-002-5",
 "- Dalsze wymagania NERC: PRC-018-1 włączono do PRC-002-2 (13.11.2014), potem PRC-002-3 (±2 ms od UTC), a dla źródeł falownikowych PRC-028-1 (2024/2025; ±1 ms i ±100 ms). Ta droga jest zbieżna z rekomendacją 28 (ocena własna).",
 "- Dalsze wymagania NERC: PRC-018-1 włączono do PRC-002-2 (13.11.2014), który zawierał już wymaganie R10 (±2 ms od UTC); obecna wersja to PRC-002-5, a dla źródeł falownikowych dodano PRC-028-1 (oba zatwierdzone przez FERC 20.02.2025; ±1 ms i ±100 ms). Ta droga jest zbieżna z rekomendacją 28 (ocena własna).", 1),
("8", F01, "F1 major (consequence)",
 "blackout slide source: the draft (for the quote) and the current version",
 f"[NERC, PRC-002-3]({P23}); [Task Force",
 f"[NERC, projekt PRC-002-3, 2018]({P23}); [NERC, PRC-002-5]({P25}); [Task Force", 1),
("9", F01, "F1 major (consequence)",
 "bibliography: current version first, the 2018 draft as the source of the quoted guideline",
 f"16. NERC (2018). *PRC-002-3 Disturbance Monitoring and Reporting Requirements* (projekt 2015-09, tekst czysty). [{P23}]({P23})",
 f"16. NERC (2024). *PRC-002-5 Disturbance Monitoring and Reporting Requirements* (przyjęty przez zarząd NERC 8.10.2024, zatwierdzony przez FERC 20.02.2025). [{P25}]({P25}); projekt PRC-002-3 z wytycznymi (2018, projekt 2015-09): [{P23}]({P23})", 1),
("10", F01, "F1 minor #4 (coordinator opened the IRIS record)",
 "journal identified: IEEE Instrumentation & Measurement Magazine 25(6): 11–18 (2022), DOI 10.1109/MIM.2022.9847197",
 "22. Macii D., Rinaldi S. (b.d., ok. 2022). *Time Synchronization for Smart Grids Applications: Requirements and Uncertainty Issues* (manuskrypt przyjęty do druku; czasopisma nie sprawdzono). Repozytorium IRIS Uniwersytetu w Trydencie. [",
 "22. Macii D., Rinaldi S. (2022). Time Synchronization for Smart Grids Applications: Requirements and Uncertainty Issues. *IEEE Instrumentation & Measurement Magazine* 25(6): 11–18. [https://doi.org/10.1109/MIM.2022.9847197](https://doi.org/10.1109/MIM.2022.9847197); manuskrypt przyjęty do druku (repozytorium IRIS Uniwersytetu w Trydencie): [", 1),
("11", F01, "F1 minor #5 (coordinator opened the NIST glossary)",
 "the historian paraphrase described the control centre; NIST glossary definition of data historian",
 "| archiwum danych procesowych (ang. historian) | przechowuje i rejestruje informacje zebrane w obiektach terenowych | dane 10-minutowe turbin |",
 "| archiwum danych procesowych (ang. historian) | scentralizowana baza danych wspierająca analizę danych metodami statystycznego sterowania procesem (słownik NIST) | dane 10-minutowe turbin |", 1),
("12", F01, "F1 minor #5 (source)",
 "add the NIST glossary entry for data historian",
 "Źródło: [NIST SP 800-82r3](https://doi.org/10.6028/NIST.SP.800-82r3); [NIST CSRC, słownik: RTU](https://csrc.nist.gov/glossary/term/remote_terminal_unit)",
 "Źródło: [NIST SP 800-82r3](https://doi.org/10.6028/NIST.SP.800-82r3); [NIST CSRC, słownik: RTU](https://csrc.nist.gov/glossary/term/remote_terminal_unit); [NIST CSRC, słownik: data historian](https://csrc.nist.gov/glossary/term/data_historian)", 1),
("13", F01, "F1 minor #5 (bibliography)",
 "add the data historian glossary URL to entry 12",
 "12. NIST (b.d.). *CSRC Glossary: remote terminal unit (RTU)*. [https://csrc.nist.gov/glossary/term/remote_terminal_unit](https://csrc.nist.gov/glossary/term/remote_terminal_unit)",
 "12. NIST (b.d.). *CSRC Glossary: remote terminal unit (RTU)*. [https://csrc.nist.gov/glossary/term/remote_terminal_unit](https://csrc.nist.gov/glossary/term/remote_terminal_unit); *data historian*: [https://csrc.nist.gov/glossary/term/data_historian](https://csrc.nist.gov/glossary/term/data_historian)", 1),
("14", F01, "F1 minor #6",
 "T13-03 Table 1 = parameters measured in real time (adapted from IEC 61724); 'durations of system outage'",
 "- PV: minimalny zestaw parametrów wg IEA PVPS T13-03:2014 (tabl. 1) obejmuje także czas trwania przerw.",
 "- PV: tabl. 1 raportu IEA PVPS T13-03:2014 (parametry mierzone w czasie rzeczywistym, wg IEC 61724) obejmuje także czas trwania przestojów systemu.", 1),
("15", F01, "F1 minor #7",
 "BMS belongs to level 2 as on the diagram; SOC/SOH are BMS estimates",
 "| BESS | BMS: stan naładowania, stan zdrowia, temperatura ogniw | lokalny EMS: zarządzanie urządzeniami, sterowanie PCS, komunikacja |",
 "| BESS | pomiary ogniw: napięcie, prąd, temperatura (ocena własna) | BMS (m.in. stan naładowania, stan zdrowia, temperatura ogniw); lokalny EMS: zarządzanie urządzeniami, sterowanie PCS, komunikacja |", 1),
("16", F01, "F1 minor #9",
 "the release says 'no risk to the WECs' and 'no SCADA monitoring', not that the turbines kept producing",
 "- Wniosek (ocena własna): utrata łącza monitoringu nie zatrzymała bezpiecznej pracy, bo sterowanie i zabezpieczenia działają lokalnie, a kanał operatora sieci był oddzielny; opóźniła jednak diagnostykę i serwis zdalny.",
 "- Wniosek (ocena własna): według producenta utrata łącza monitoringu nie stworzyła zagrożenia dla turbin, bo sterowanie i zabezpieczenia działają lokalnie, a kanał operatora sieci był oddzielny; zabrakło jednak zdalnego monitoringu, diagnostyki i serwisu.", 1),
("17", F01, "F1 minor #9 (notes)",
 "same point in the notes",
 "Typowe nieporozumienie: brak łączności oznacza postój instalacji. Tu instalacja pracowała, tylko nikt z zewnątrz jej nie widział.",
 "Typowe nieporozumienie: brak łączności oznacza zagrożenie albo postój instalacji. Według komunikatu turbiny nie były zagrożone, a operatorzy sieci mieli do nich dostęp; zabrakło zdalnego monitoringu SCADA i serwisu.", 1),
("18", F01, "F1 minor #10",
 "Maldonado-Correa: conditional economic argument, not causal",
 "turbin wiatrowych służą też do monitorowania stanu, bo nie wymagają dodatkowych czujników ani sprzętu akwizycji (przegląd Maldonado-Correa i in., 2020).",
 "turbin wiatrowych są atrakcyjną ekonomicznie podstawą monitorowania stanu, bo nie wymagają dodatkowych czujników ani sprzętu akwizycji (przegląd Maldonado-Correa i in., 2020).", 1),
("19", F01, "F1 minor #13",
 "IEC/IEEE 61850-9-3:2016 stability date 2026",
 "Precision time protocol profile for power utility automation*, wyd. 1.0. [",
 "Precision time protocol profile for power utility automation*, wyd. 1.0 (data stabilności 2026 — przed zajęciami sprawdzić). [", 1),
("20", F01, "F1 minor #14",
 "one label for T13-03 in all bibliographies",
 "Performance Analysis* (IEA PVPS T13-03:2014). IEA PVPS.",
 "Performance Analysis* (Report IEA-PVPS T13-03:2014). IEA PVPS.", 1),
("21", F01, "coordinator",
 "PLC expansion as in W1 and W2",
 "PLC (Programmable Logic Controller — sterownik programowalny)",
 "PLC (Programmable Logic Controller — programowalny sterownik logiczny)", 1),
("22", F01, "coordinator (notes)",
 "PLC term in the notes",
 "Sterownik programowalny wykonuje program:",
 "Sterownik PLC wykonuje program:", 1),
# ---------------- 02 ----------------
("23", F02, "F1 minor #14",
 "one label for T13-03 in all bibliographies",
 "Performance Analysis* (IEA PVPS T13-03:2014). IEA PVPS.",
 "Performance Analysis* (Report IEA-PVPS T13-03:2014). IEA PVPS.", 1),
("24", F02, "F1 minor #11",
 "define k so that the alias falls in 0…f_s/2",
 "gdzie $k$ jest liczbą całkowitą — to **aliasing**.",
 "gdzie $k$ jest liczbą całkowitą dobraną tak, by wynik leżał w przedziale od 0 do $f_s/2$ — to **aliasing**.", 1),
("25", F02, "F1 minor #12",
 "loop budget must hold for the NE 43 high failure current (≥ 21 mA); 22 mA gives ≈ 614 Ω",
 "- Minimalne napięcie i dopuszczalne obciążenie konkretnego przetwornika podaje jego karta katalogowa; tu przyjęto je umownie.",
 "- Minimalne napięcie i dopuszczalne obciążenie konkretnego przetwornika podaje jego karta katalogowa; tu przyjęto je umownie. Budżet sprawdza się dla największego prądu: przy sygnale uszkodzenia ≥ 21 mA ([część 5](./05-uszkodzenia-toru-i-przyklad-biogazowy.mdx)), np. 22 mA, $R_{max} = 13{,}5\\ \\mathrm{V} / 0{,}022\\ \\mathrm{A} \\approx 614\\ \\Omega$, nadal więcej niż 285 Ω (ocena własna).", 1),
("26", F02, "coordinator (slide density)",
 "slide 1 too long for one screen: the terminology note moves to the notes",
 "- Polskie nazwy to powszechne terminy techniczne: polskiego VIM (PKN-ISO/IEC Guide 99:2010) nie ma w wolnym dostępie, dlatego podajemy terminy angielskie.\n- Kolejne slajdy omawiają bloki schematu: pętla 4–20 mA i protokół HART (Highway Addressable Remote Transducer), przetwornik analogowo-cyfrowy, próbkowanie, uśrednianie, zapis.\n",
 "", 1),
("27", F02, "coordinator (notes)",
 "terminology note in the notes",
 "Słownik VIM daje nam wspólny język. Czujnik",
 "Słownik VIM daje nam wspólny język. Polskie nazwy to powszechne terminy techniczne: polskiego wydania VIM (PKN-ISO/IEC Guide 99:2010) nie ma w wolnym dostępie, dlatego przy każdym podaję termin angielski. Czujnik", 1),
("28", F02, "coordinator (consequence of 26)",
 "HART expanded at first use in text",
 "- Protokół **HART** nakłada",
 "- Protokół **HART** (Highway Addressable Remote Transducer) nakłada", 1),
("29", F02, "F2 minor #4",
 "an Amendment is 'zmiana' in PN usage",
 "zał. F; w 2026 r. wydano poprawkę JCGM 100:2008/Amd.1:2026.",
 "zał. F; w 2026 r. wydano zmianę 1 (JCGM 100:2008/Amd.1:2026, nieliniowość modeli pomiaru).", 1),
# ---------------- 03 ----------------
("30", F03, "F2 minor #4",
 "an Amendment is 'zmiana'",
 "to JCGM 100:2008, z poprawką Amd.1:2026.",
 "to JCGM 100:2008 ze zmianą 1 (JCGM 100:2008/Amd.1:2026, nieliniowość modeli pomiaru).", 1),
("31", F03, "F2 minor #4 (bibliography)",
 "an Amendment is 'zmiana'",
 ", wyd. 1, z poprawką Amd.1:2026. BIPM.",
 ", wyd. 1, ze zmianą 1 (Amd.1:2026). BIPM.", 1),
("32", F03, "F2 minor #5 (coordinator opened the EA PDF: EA-4/02 M:2022 rev03, 4.04.2022)",
 "cite EA's own copy",
 "(dokument EA, European co-operation for Accreditation — europejska współpraca w dziedzinie akredytacji; kopia udostępniona przez hiszpańską jednostkę akredytującą ENAC), pkt 5.1",
 "(dokument EA, European co-operation for Accreditation — europejska współpraca w dziedzinie akredytacji; rev03 z 4.04.2022), pkt 5.1", 1),
("33", F03, "F2 minor #5 (source line)",
 "EA URL",
 f"[EA-4/02 M:2022, kopia ENAC]({ENAC})",
 f"[EA-4/02 M:2022]({EA})", 1),
("34", F03, "F2 minor #5 (bibliography)",
 "EA URL",
 f"6. EA (2022). *EA-4/02 M:2022 Evaluation of the Uncertainty of Measurement in Calibration*. European co-operation for Accreditation (kopia udostępniona przez ENAC). [{ENAC}]({ENAC})",
 f"6. EA (2022). *EA-4/02 M:2022 Evaluation of the Uncertainty of Measurement in Calibration*, rev03 (4.04.2022). European co-operation for Accreditation. [{EA}]({EA})", 1),
("35", F03, "F2 minor #3 (coordinator opened the Vademecum)",
 "use the official Polish wording of VIM 2.39 and its Note 2 (Vademecum 2022)",
 "- **Wzorcowanie** (ang. calibration, VIM 2.39): działanie, które w określonych warunkach w pierwszym kroku ustala zależność między wartościami odtwarzanymi przez wzorzec pomiarowy (z ich niepewnościami) a wskazaniami przyrządu, a w drugim kroku wykorzystuje ją do uzyskiwania wyniku pomiaru ze wskazania (tłumaczenie własne; początek definicji jak w Vademecum Głównego Urzędu Miar).\n- Wg VIM (uwaga 2 do 2.39) wzorcowania nie należy mylić z adiustacją układu pomiarowego (regulacją, często błędnie nazywaną „samokalibracją”) ani ze sprawdzeniem wzorcowania.",
 "- **Wzorcowanie** (ang. calibration, VIM 2.39): „działanie, które w określonych warunkach, w pierwszym kroku ustala zależność pomiędzy odwzorowywanymi przez wzorzec pomiarowy wartościami wielkości wraz z ich niepewnościami pomiaru, a odpowiadającymi im wskazaniami wraz z ich niepewnościami, natomiast w drugim kroku wykorzystuje tę informację do ustalenia zależności pozwalającej uzyskać wynik pomiaru na podstawie wskazania” (brzmienie wg Vademecum Głównego Urzędu Miar, 2022).\n- Uwaga 2 do 2.39: „Wzorcowania nie należy mylić z adiustacją układu pomiarowego, często mylnie nazywaną »samowzorcowaniem«, ani z weryfikacją wzorcowania”.", 1),
("36", F03, "F2 minor #6",
 "ILAC-G24 4.2 a) and b) wording",
 "ponowne wzorcowanie ma m.in. oszacować odchyłkę od wartości odniesienia i potwierdzić deklarowaną niepewność (4.2).",
 "ponowne wzorcowanie ma m.in. oszacować odchyłkę od wartości odniesienia i jej niepewność w chwili użycia przyrządu oraz wesprzeć walidację wymaganej lub deklarowanej niepewności (4.2).", 1),
("37", F03, "F2 minor #7 (verified-facts W03, DA-06 3.1.1–3.1.2)",
 "3.1.1 lists four routes; route 4 needs evidence (3.1.2)",
 "których jednostka akredytująca jest sygnatariuszem porozumień o wzajemnym uznawaniu EA MLA lub ILAC MRA.",
 "których jednostka akredytująca jest sygnatariuszem porozumień o wzajemnym uznawaniu EA MLA lub ILAC MRA. Pkt 3.1.1 dopuszcza też wzorcowanie poza tymi porozumieniami; dla laboratorium spoza ILAC MRA pkt 3.1.2 wymaga m.in. miarodajnych dowodów zasadności takiego wyboru i audytów dostawcy.", 1),
("38", F03, "F2 could-not-verify note (literal translation)",
 "VIM 4.21 'incremental' = 'przyrostowa'",
 "ciągła lub skokowa zmiana wskazania w czasie",
 "ciągła lub przyrostowa zmiana wskazania w czasie", 1),
# ---------------- 04 ----------------
("39", F04, "F2 major #1–#2 (coordinator opened IEC webstore 68500, 69216 and the 50-1 sample)",
 "2022 restructuring: 12-1 power curve, 12-2:2022 nacelle anemometry (current), 50-1:2022 wind measurement incl. anemometer classification, calibration, in-situ comparison",
 "- IEC 61400-12-1:2022 (wyd. 3.0 z 5.09.2022, z poprawką z 05.2025) zastąpiła IEC 61400-12-1:2017 i IEC 61400-12-2:2013 (anemometria gondolowa). Załączniki normatywne: F — wzorcowanie anemometrów w tunelu aerodynamicznym; I — klasyfikacja anemometrii czaszowej i ultradźwiękowej; J — jej ocena; K — porównanie anemometrów na miejscu pomiaru.",
 "- W 2022 r. serię IEC 61400-12 przebudowano: IEC 61400-12-1:2022 (wyd. 3.0 z 5.09.2022, z poprawką z 05.2025) opisuje pomiar krzywej mocy, IEC 61400-12-2:2022 (wyd. 2.0) wariant z anemometrem na gondoli, a IEC 61400-50-1:2022 (wyd. 1.0 z 16.11.2022) pomiar wiatru. Razem zastąpiły IEC 61400-12-1:2017 i IEC 61400-12-2:2013.\n- IEC 61400-50-1:2022 opisuje klasyfikację i ocenę anemometrów czaszowych i ultradźwiękowych (rozdz. 6–7), wzorcowanie w tunelu aerodynamicznym z analizą niepewności (rozdz. 8) i porównanie anemometrów na miejscu pomiaru (rozdz. 9).", 1),
("40", F04, "F2 major (notes)",
 "the notes said the series was merged — it was split",
 "W 2022 roku pomiary krzywej mocy, łącznie z anemometrią gondolową, zebrano w jednej normie, więc nie cytujemy już osobnej części 12-2.",
 "W 2022 roku serię norm przebudowano: krzywa mocy, wariant z anemometrem na gondoli i sam pomiar wiatru mają teraz osobne części, a klasyfikacja i wzorcowanie anemometrów trafiły do IEC 61400-50-1.", 1),
("41", F04, "F2 major (source line)",
 "sources for 12-2:2022 and 50-1:2022",
 "[IEC 61400-12-1:2022, próbka normy](https://cdn.standards.iteh.ai/samples/105156/3a4f433b403c4d9bababf32e1b9b13f3/IEC-61400-12-1-2022.pdf); [MEASNET",
 "[IEC 61400-12-1:2022, próbka normy](https://cdn.standards.iteh.ai/samples/105156/3a4f433b403c4d9bababf32e1b9b13f3/IEC-61400-12-1-2022.pdf); [IEC 61400-12-2:2022](https://webstore.iec.ch/en/publication/68500); [IEC 61400-50-1:2022](https://webstore.iec.ch/en/publication/69216); [IEC 61400-50-1:2022, próbka normy](https://cdn.standards.iteh.ai/samples/105556/722392eb3aa44751a32a7172b86f7ced/IEC-61400-50-1-2022.pdf); [MEASNET", 1),
("42", F04, "F2 major (bibliography)",
 "entries 23–24 for 12-2:2022 and 50-1:2022",
 "22. Lindig S., Louwen A., Moser D., Topic M. (2020). Outdoor PV System Monitoring—Input Data Quality, Data Imputation and Filtering Approaches. *Energies* 13(19): 5099. [https://doi.org/10.3390/en13195099](https://doi.org/10.3390/en13195099)\n",
 "22. Lindig S., Louwen A., Moser D., Topic M. (2020). Outdoor PV System Monitoring—Input Data Quality, Data Imputation and Filtering Approaches. *Energies* 13(19): 5099. [https://doi.org/10.3390/en13195099](https://doi.org/10.3390/en13195099)\n23. IEC (2022). *IEC 61400-12-2:2022 Wind energy generation systems — Part 12-2: Power performance of electricity producing wind turbines based on nacelle anemometry*, wyd. 2.0. [https://webstore.iec.ch/en/publication/68500](https://webstore.iec.ch/en/publication/68500)\n24. IEC (2022). *IEC 61400-50-1:2022 Wind energy generation systems — Part 50-1: Wind measurement — Application of meteorological mast, nacelle and spinner mounted instruments*, wyd. 1.0. [https://webstore.iec.ch/en/publication/69216](https://webstore.iec.ch/en/publication/69216); próbka normy (iTeh): [https://cdn.standards.iteh.ai/samples/105556/722392eb3aa44751a32a7172b86f7ced/IEC-61400-50-1-2022.pdf](https://cdn.standards.iteh.ai/samples/105556/722392eb3aa44751a32a7172b86f7ced/IEC-61400-50-1-2022.pdf)\n", 1),
("43", F04, "F2 minor #8",
 "only the normative reference to IEC 60904-5 is verifiable",
 "Zamiast czujnika na tylnej powierzchni można wyznaczyć równoważną temperaturę ogniwa z napięcia obwodu otwartego (IEC 60904-5, powołana w IEC 61724-1:2021).",
 "IEC 61724-1:2021 powołuje normatywnie IEC 60904-5 (równoważna temperatura ogniwa wyznaczana z napięcia obwodu otwartego); sposób jej użycia trzeba sprawdzić w tekście normy.", 1),
("44", F04, "F2 minor #9",
 "Tang: constrained bandwidth in low-frequency options",
 "| mały dryft zera i duża dokładność; ograniczone pasmo, większy pobór prądu |",
 "| mały dryft zera i duża dokładność; w wersjach niskoczęstotliwościowych ograniczone pasmo; większy pobór prądu |", 1),
("45", F04, "F2 minor #10",
 "full author list, volume and article number",
 "11. Tang C. i in. (2024). Review of the current transducer techniques. *Discover Applied Sciences*. [",
 "11. Tang C., Liang J., Zhu Q., Lu X., Shu J., Jiang C. (2024). Review of the current transducer techniques. *Discover Applied Sciences* 6: 351. [", 1),
("46", F04, "F2 minor #12",
 "Table 1 of IEC 61724-1, not of T13-03",
 "| próbkowanie i zapis | próbkowanie co 1 s lub częściej, zapis średnich co 5–15 min; wymagania klasy: tabl. 1 | IEA PVPS T13-03 |",
 "| próbkowanie i zapis | próbkowanie co 1 s lub częściej, zapis średnich co 5–15 min; wymagania klasy: tabl. 1 IEC 61724-1:2021 | IEA PVPS T13-03; tekst normy |", 1),
("47", F04, "F2 minor #11",
 "T13-03 says nothing about UTC",
 "dostępność danych co najmniej 99%, poniżej 95% — system akwizycji niskiej jakości | IEA PVPS T13-03 |",
 "dostępność danych co najmniej 99%, poniżej 95% — system akwizycji niskiej jakości | część 1 (UTC); IEA PVPS T13-03 (dostępność) |", 1),
("48", F04, "F2 minor #13",
 "ranges attributed to HSE 2004",
 "| tlen 0–100%, gazy toksyczne 0–1000 ppm; starzenie ([część 3](./03-niepewnosc-i-wzorcowanie.mdx)) |",
 "| zakresy wg HSE (2004): tlen 0–100%, gazy toksyczne 0–1000 ppm; starzenie ([część 3](./03-niepewnosc-i-wzorcowanie.mdx)) |", 1),
("49", F04, "F2 minor #14",
 "the gloss is not in Reda",
 "(„półprzewodnikowy” oznacza tu piranometr z fotodiodą, a nie ogniwo referencyjne):",
 "(„półprzewodnikowy” oznacza tu piranometr z fotodiodą, a nie ogniwo referencyjne — zasada podręcznikowa):", 1),
("50", F04, "F2 minor #15",
 "own inference labelled",
 "Dlatego temperaturę modułu mierzy się razem z temperaturą otoczenia i prędkością wiatru.",
 "Dlatego temperaturę modułu warto mierzyć razem z temperaturą otoczenia i prędkością wiatru (ocena własna).", 1),
("51", F04, "F2 minor #15",
 "undated normative references",
 "IEC 61724-1:2021 powołuje normatywnie IEC 61557-12 (urządzenia",
 "IEC 61724-1:2021 powołuje normatywnie (bez daty wydania) IEC 61557-12 (urządzenia", 1),
("52", F04, "F2 optional (verified by checker 2 in the IEC sample)",
 "primary support from the Introduction of IEC 61724-1",
 "Tak opisuje je producent czujników (Hukseflux); tego zdania nie cytujemy z tekstu normy.",
 "Tak opisuje je producent czujników (Hukseflux); tego zdania nie cytujemy z tekstu normy. Sam wstęp normy mówi, że większe systemy PV powinny mieć więcej punktów monitoringu i czujniki o większej dokładności (tłumaczenie własne).", 1),
# ---------------- 05 ----------------
("53", F05, "F3 minor #1",
 "para 99 adopts the lesson of the Baker report on Texas City",
 "Wniosek raportu (pkt 99): systemy ochrony bezpieczeństwa procesowego nie powinny polegać na reakcji operatora na alarmy, a zabezpieczenie przed przepełnieniem powinno być niezależne od zwykłego monitoringu ruchowego.",
 "Raport (pkt 99) przywołuje wniosek raportu Bakera po Texas City — systemy ochrony bezpieczeństwa procesowego nie powinny polegać na reakcji operatora na alarmy, a zabezpieczenie przed przepełnieniem powinno być niezależne od zwykłego monitoringu ruchowego — i stwierdza, że tę lekcję trzeba wyciągnąć także z Buncefield.", 1),
("54", F05, "F3 minor #2",
 "DC partly from expert judgement and certificates; automatic tests incl. external diagnostics",
 "- Dane SINTEF dla przetworników z norweskiego przemysłu naftowego i gazowego: **pokrycie diagnostyczne** (DC, ang. diagnostic coverage), czyli udział uszkodzeń niebezpiecznych wykrywanych automatycznie, wynosi 65% dla przetworników ciśnienia i przepływu oraz 70% dla poziomu i temperatury.",
 "- Wg SINTEF (λDU z danych eksploatacyjnych norweskiego przemysłu naftowego i gazowego; DC ustalone m.in. na podstawie ocen ekspertów i certyfikatów) **pokrycie diagnostyczne** (DC, ang. diagnostic coverage), czyli udział uszkodzeń niebezpiecznych wykrywanych przez testy automatyczne (autodiagnostyka urządzenia i diagnostyka zewnętrzna), wynosi 65% dla przetworników ciśnienia i przepływu oraz 70% dla poziomu i temperatury.", 1),
("55", F05, "F3 minor #2 (notes)",
 "automatic diagnostics, not only self-diagnostics",
 "autodiagnostyka przetwornika wykrywa około dwóch trzecich uszkodzeń niebezpiecznych",
 "diagnostyka automatyczna wykrywa około dwóch trzecich uszkodzeń niebezpiecznych", 1),
("56", F05, "F3 minor #3",
 "the 2025 NAMUR item is an abstract, not a change list",
 "Wydanie z 2025 r. ujednolica ich kolory i symbole na ekranach i diodach.",
 "Zalecenie (wyd. 2025) określa jednolite kolory i symbole sygnałów statusu na ekranach i diodach LED.", 1),
("57", F05, "F3 minor #4",
 "the standard expands UPS as uninterruptible power systems; PN title 'Systemy bezprzerwowego zasilania (UPS)'",
 "UPS (Uninterruptible Power Supply — zasilacz bezprzerwowy); tak brzmi tytuł normy.",
 "UPS (ang. uninterruptible power system — system bezprzerwowego zasilania); tak brzmi tytuł normy.", 1),
("58", F05, "F3 minor #4 (source)",
 "official IEC page",
 "[IEC 62040-3:2021, próbka normy](https://cdn.standards.iteh.ai/samples/100462/e539fa74c78f44208501e78afde62152/IEC-62040-3-2021.pdf)",
 "[IEC 62040-3:2021, próbka normy](https://cdn.standards.iteh.ai/samples/100462/e539fa74c78f44208501e78afde62152/IEC-62040-3-2021.pdf); [IEC, IEC 62040-3:2021](https://webstore.iec.ch/en/publication/60140)", 1),
("59", F05, "F3 minor #4 (bibliography)",
 "official IEC page",
 "próbka normy (iTeh). [https://cdn.standards.iteh.ai/samples/100462/e539fa74c78f44208501e78afde62152/IEC-62040-3-2021.pdf](https://cdn.standards.iteh.ai/samples/100462/e539fa74c78f44208501e78afde62152/IEC-62040-3-2021.pdf)",
 "próbka normy (iTeh). [https://cdn.standards.iteh.ai/samples/100462/e539fa74c78f44208501e78afde62152/IEC-62040-3-2021.pdf](https://cdn.standards.iteh.ai/samples/100462/e539fa74c78f44208501e78afde62152/IEC-62040-3-2021.pdf); strona IEC: [https://webstore.iec.ch/en/publication/60140](https://webstore.iec.ch/en/publication/60140)", 1),
("60", F05, "F3 minor #5",
 "the alarm-and-record sentence is TRAS 2.6.3(4)",
 "| TRAS 120 (alarm i rejestracja); reszta: ocena własna |",
 "| TRAS 120, 2.6.3(4) (alarm i rejestracja); reszta: ocena własna |", 1),
("61", F05, "F3 minor #6 (coordinator opened FNR Basisdaten, p. 51)",
 "source for the methane energy content",
 "wartość opałowa metanu ok. 9,97 kWh/m³ w warunkach normalnych;",
 "wartość opałowa metanu ok. 9,97 kWh/m³ w warunkach normalnych (FNR, Basisdaten Bioenergie Deutschland 2024, s. 51);", 1),
("62", F05, "F3 minor #6",
 "label sentence",
 "wartość opałowa metanu to stała z tablic,",
 "wartość opałowa metanu pochodzi z tablic FNR,", 1),
("63", F05, "F3 minor #6 (source line)",
 "FNR link",
 "[Beharrysingh i in., 2018](https://oaktrust.library.tamu.edu/server/api/core/bitstreams/5553932f-d7dc-46c4-afdd-aa09a086fe66/content); obliczenia własne",
 f"[Beharrysingh i in., 2018](https://oaktrust.library.tamu.edu/server/api/core/bitstreams/5553932f-d7dc-46c4-afdd-aa09a086fe66/content); [FNR, Basisdaten Bioenergie 2024]({FNR}); obliczenia własne", 1),
("64", F05, "F3 minor #6 (bibliography)",
 "entry 17 FNR",
 "16. Beharrysingh A., Hernandez M., Ng C., Maher C. (2018). Process Safety Time Analysis for Upstream Facilities. 21st Annual International Symposium, Mary Kay O'Connor Process Safety Center, Texas A&M University. [https://oaktrust.library.tamu.edu/server/api/core/bitstreams/5553932f-d7dc-46c4-afdd-aa09a086fe66/content](https://oaktrust.library.tamu.edu/server/api/core/bitstreams/5553932f-d7dc-46c4-afdd-aa09a086fe66/content)\n",
 f"16. Beharrysingh A., Hernandez M., Ng C., Maher C. (2018). Process Safety Time Analysis for Upstream Facilities. 21st Annual International Symposium, Mary Kay O'Connor Process Safety Center, Texas A&M University. [https://oaktrust.library.tamu.edu/server/api/core/bitstreams/5553932f-d7dc-46c4-afdd-aa09a086fe66/content](https://oaktrust.library.tamu.edu/server/api/core/bitstreams/5553932f-d7dc-46c4-afdd-aa09a086fe66/content)\n17. FNR (2023). *Basisdaten Bioenergie Deutschland 2024*. Fachagentur Nachwachsende Rohstoffe e.V. [{FNR}]({FNR})\n", 1),
("65", F05, "F3 minor #7",
 "edition and clause as quoted",
 "definicja IEC 61511-1 w brzmieniu cytowanym przez Beharrysingha i in. (2018)",
 "definicja IEC 61511-1:2016 (3.2.52.1) w brzmieniu cytowanym przez Beharrysingha i in. (2018)", 1),
("66", F05, "F3 minor #8",
 "Buncefield: the independent switch existed but was inoperable — independence plus proven function",
 "a niezależność urządzenia maksimum jest ważniejsza niż jego precyzja (Buncefield).",
 "a niezależność i potwierdzona testami sprawność urządzenia maksimum są ważniejsze niż jego precyzja (por. Buncefield: niezależny wyłącznik był niesprawny).", 1),
("67", F05, "F3 minor #9",
 "'too slow' contradicts the slide's own numbers; TRAS 2.4(8) condition",
 "ale jest zbyt wolna i pośrednia, by być główną warstwą ochrony zbiornika. Tę rolę pełni pomiar napełnienia z ograniczeniem poboru gazu, a pomiar O₂ jest rozwiązaniem TRAS 120 (2.4(8)) dla instalacji istniejących.",
 "ale jest pośrednia i zależy od sprawności linii poboru (kondensat, adsorpcja, cykl przełączania), więc nie powinna być główną warstwą ochrony zbiornika. Tę rolę pełni pomiar napełnienia z ograniczeniem poboru gazu. Pomiar O₂ TRAS 120 (2.4(8)) wymaga w instalacjach istniejących, w których nie zapewniono ograniczenia poboru gazu przed zadziałaniem zabezpieczenia podciśnieniowego.", 1),
("68", F05, "F3 minor #9 (notes)",
 "same point in the notes",
 "Dla sterowania dozowaniem powietrza to nie problem, dla ochrony zbiornika tak, dlatego główną ochronę daje napełnienie, a nie skład gazu.",
 "Dla sterowania dozowaniem powietrza to nie problem; dla ochrony zbiornika ważniejsze jest, że pomiar jest pośredni i zależy od linii poboru, dlatego główną ochronę daje napełnienie, a nie skład gazu.", 1),
("69", F05, "F3 minor #10",
 "one Polish term for t_x: czas odpowiedzi",
 "rozróżnia **czas ustalania wskazania** $t_x$ (niem. Einstellzeit)",
 "rozróżnia **czas odpowiedzi** $t_x$ (niem. Einstellzeit; por. czas odpowiedzi na skok, [część 2](./02-tor-pomiarowy.mdx))", 1),
("70", F05, "F3 minor #10",
 "one Polish term for t_x",
 "transport gazu, czas ustalania wskazania i czas, po którym środek ochronny zaczyna działać (T 023).",
 "transport gazu, czas odpowiedzi i czas, po którym środek ochronny zaczyna działać (T 023).", 1),
("71", F05, "F3 minor #10 (notes)",
 "one Polish term for t_x",
 "Do tego dochodzi czas ustalania wskazania analizatora,",
 "Do tego dochodzi czas odpowiedzi analizatora,", 1),
("72", F05, "F3 minor #11 (coordinator opened CSB p. 23 and Appendix S)",
 "Texas City: calibration for SG 0,8 and a declining indication, not only the range",
 "W Texas City zakres pomiarowy obejmował normalną pracę, a nie awarię.",
 "W Texas City zakres obejmował tylko dolną część kolumny, a przetwornik był wzorcowany dla gęstości względnej 0,8 (CSB, dodatek S); wg CSB wskazanie pokazywało spadek poziomu, gdy kolumna była przepełniana.", 1),
# ---------------- 06 ----------------
("73", F06, "F1 major (consequence)",
 "current NERC version",
 "PRC-002-3 (R10) wymaga ±2 ms od UTC",
 "PRC-002-5 (R10) wymaga ±2 ms od UTC", 1),
("74", F06, "F3 minor #13",
 "all three local-autonomy rules are own judgement",
 "Funkcje chroniące ludzi i urządzenia działają lokalnie i nie zależą od łącza ani od chmury — to kryterium niezależności warstwy ochrony z W1. Buforowanie danych i komunikat „brak danych” zamiast „0 kW” to zasady projektowe (ocena własna), które trzeba wpisać do specyfikacji, bo w przejrzanych źródłach nie znaleźliśmy ich jako wymagania.",
 "Wszystkie trzy to zasady projektowe z części 1 (ocena własna). Lokalne działanie funkcji chroniących ludzi i urządzenia wynika z kryterium niezależności warstwy ochrony z W1. Buforowanie danych i komunikat „brak danych” zamiast „0 kW” trzeba wpisać do specyfikacji, bo w przejrzanych źródłach nie znaleźliśmy ich jako wymagania.", 1),
("75", F06, "F3 minor #13 (summary)",
 "mark the rules as own judgement",
 "a portal pokazuje „brak danych”, a nie „0” ([część 1](./01-cele-architektura-i-czas.mdx)).",
 "a portal pokazuje „brak danych”, a nie „0” (zasady projektowe — ocena własna; [część 1](./01-cele-architektura-i-czas.mdx)).", 1),
("76", F06, "F3 minor #1 (quiz Q9)",
 "para 99 adopts the Baker lesson",
 "Raport z 2011 r. (pkt 99): systemy ochrony bezpieczeństwa procesowego nie powinny polegać na reakcji operatora na alarmy, a zabezpieczenie przed przepełnieniem powinno być niezależne od zwykłego monitoringu ruchowego.",
 "Raport z 2011 r. (pkt 99) przywołuje wniosek raportu Bakera po Texas City: systemy ochrony bezpieczeństwa procesowego nie powinny polegać na reakcji operatora na alarmy, a zabezpieczenie przed przepełnieniem powinno być niezależne od zwykłego monitoringu ruchowego; tę lekcję trzeba wyciągnąć także z Buncefield.", 1),
("77", F06, "F3 minor #12 (quiz Q10)",
 "13,6 m³ as on page 05",
 "(U ≈ 1,4% zakresu, czyli ok. 14 m³)",
 "(U ≈ 1,4% zakresu, czyli ok. 13,6 m³)", 1),
("78", F06, "F3 minor #8 (quiz Q10)",
 "own judgement; independence plus proven function",
 "— ta niezależność jest ważniejsza niż precyzja pomiaru.",
 "— ta niezależność, potwierdzona testami, jest ważniejsza niż precyzja pomiaru (ocena własna).", 1),
# ---------------- index ----------------
("79", FIX, "F2 minor #4",
 "an Amendment is 'zmiana'",
 ", wyd. 1, z poprawką Amd.1:2026. BIPM.",
 ", wyd. 1, ze zmianą 1 (Amd.1:2026). BIPM.", 1),
]
