# Accepted fixes for W2 (29.09.2026). Each entry: (id, file, severity/source, note, old, new, count)
# count = expected number of occurrences of `old` (all are replaced).
L = "/mnt/user-data/outputs/lecture/wyklad-02-analiza-ryzyka/"

FIXES = [
# ---------------- 01 ----------------
("1", "01-proces-zarzadzania-ryzykiem.mdx", "F1 minor",
 "ISO 31000 6.3.4 addresses the organization; 'regulator' is own judgement",
 "- Kryteria ryzyka ustala organizacja lub regulator na etapie kontekstu, przed analizą (ISO 31000:2018, 6.3.4); ewaluacja porównuje z nimi wynik (6.4.4).",
 "- Kryteria ryzyka organizacja określa przed oceną ryzyka, na etapie kontekstu (ISO 31000:2018, 6.3.4); ewaluacja porównuje z nimi wynik (6.4.4). Wartości liczbowe może też narzucać regulator (ocena własna).", 1),
("2", "01-proces-zarzadzania-ryzykiem.mdx", "F1 minor",
 "Stanley 2018 §5.4: 10⁻⁵ = middle of ALARP region; 10⁻⁶ for firms aiming at the broadly acceptable line; order-of-magnitude cut is cited practice",
 "- Cel dla jednego scenariusza w LOPA ustala się niżej niż granicę dla osoby, bo ta sama osoba jest narażona także na inne ryzyka: Stanley i in. (2018) obniżają granicę dla pracowników o rząd wielkości i wskazują np. 10⁻⁵ /rok albo ostrożniej 10⁻⁶ /rok. Wrócimy do tego w [części 5](./05-lopa-i-sil.mdx).",
 "- Cel dla jednego scenariusza w LOPA ustala się niżej niż granicę dla osoby, bo ta sama osoba jest narażona także na inne ryzyka. Stanley i in. (2018) przytaczają praktykę obniżania granicy nietolerowanej dla pracowników o rząd wielkości (do 10⁻⁴ /rok) i proponują cel w środku obszaru ALARP, 10⁻⁵ /rok; firmy, które chcą ograniczyć ciężar wykazywania ALARP, mogą przyjąć 10⁻⁶ /rok. Wrócimy do tego w [części 5](./05-lopa-i-sil.mdx).", 1),
("3", "01-proces-zarzadzania-ryzykiem.mdx", "F1 minor",
 "Cox: matrices 'can assign identical ratings' (modality)",
 "i nadaje tę samą ocenę ilościowo bardzo różnym ryzykom (kompresja zakresu).",
 "i może nadać tę samą ocenę ilościowo bardzo różnym ryzykom (kompresja zakresu).", 1),
("4", "01-proces-zarzadzania-ryzykiem.mdx", "F1 minor",
 "Baybutt 2016: reversals 'may occur' (modality)",
 "- Baybutt (2016) opisuje odwrócenie rankingu: wyższe ryzyko trafia do niższej kategorii, a niższe do wyższej.",
 "- Baybutt (2016) opisuje możliwe odwrócenie rankingu: wyższe ryzyko może trafić do niższej kategorii, a niższe do wyższej.", 1),
("5", "01-proces-zarzadzania-ryzykiem.mdx", "F1 minor (modified)",
 "verified-facts W02 support 'no method' for both acts; numerical criteria: only the provisions read (art. 226, § 39a)",
 "- Ani Kodeks pracy, ani rozporządzenie ogólne BHP nie wskazują metody oceny ani liczbowych kryteriów ryzyka.",
 "- Ani Kodeks pracy, ani rozporządzenie ogólne BHP nie wskazują metody oceny; art. 226 i § 39a nie podają też liczbowych kryteriów ryzyka.", 1),
("6", "01-proces-zarzadzania-ryzykiem.mdx", "F1 minor",
 "notes: scope of 'no method' to the two acts",
 "Metody żaden przepis nie narzuca, a norma PN-N-18002 jest dobrowolna.",
 "Metody nie narzuca ani Kodeks pracy, ani rozporządzenie ogólne BHP, a norma PN-N-18002 jest dobrowolna.", 1),
("7", "01-proces-zarzadzania-ryzykiem.mdx", "F1 minor",
 "IEC 31010:2019 has Table A.3 on applicability of techniques to the ISO 31000 process",
 "Połączenie rodzin z krokami ISO 31000 to ocena własna.",
 "Zastosowanie technik w krokach procesu ISO 31000 IEC 31010 zestawia w tabl. A.3; uproszczone przypisanie na schemacie to ocena własna.", 1),
("8", "01-proces-zarzadzania-ryzykiem.mdx", "F1 minor + coordinator",
 "sum-of-indices = log multiplication only for constant-factor consequence classes; the table has letters, not colours",
 "Kolory w komórkach to decyzja organizacji; tu przyjąłem regułę sumy indeksów, która odpowiada mnożeniu częstości przez skutek w skali logarytmicznej.",
 "Kategorie w komórkach to decyzja organizacji; tu przyjąłem regułę sumy indeksów, która odpowiada mnożeniu częstości przez skutek w skali logarytmicznej, o ile kolejne kategorie skutków różnią się o stały czynnik — w przykładzie przyjmujemy to umownie.", 1),
("9", "01-proces-zarzadzania-ryzykiem.mdx", "coordinator",
 "no colours in the matrix table",
 "mają ten sam kolor, choć społecznie oceniamy je zupełnie inaczej.",
 "mają tę samą kategorię, choć społecznie oceniamy je zupełnie inaczej.", 1),
("10", "01-proces-zarzadzania-ryzykiem.mdx", "coordinator",
 "no colours in the matrix table",
 "Typowe nieporozumienie: ryzyko w zielonym polu nie wymaga działań.",
 "Typowe nieporozumienie: ryzyko w kategorii A nie wymaga żadnych działań.", 1),
("11", "01-proces-zarzadzania-ryzykiem.mdx", "coordinator (checked the CIOP-PIB page 29.09.2026)",
 "CIOP-PIB page: PN-N-18002:2000 recommended a three- or five-level scale",
 "trzy stopnie ciężkości następstw i trzy stopnie prawdopodobieństwa dają ryzyko małe, średnie lub duże.",
 "trzy stopnie ciężkości następstw i trzy stopnie prawdopodobieństwa dają ryzyko małe, średnie lub duże (wydanie z 2000 r. zalecało skalę trój- albo pięciostopniową).", 1),
("12", "01-proces-zarzadzania-ryzykiem.mdx", "F1 note + coordinator",
 "CIOP-PIB page works over https (spec §5: external links https)",
 "http://archiwum.ciop.pl/22111.html",
 "https://archiwum.ciop.pl/22111.html", 3),
# ---------------- 02 ----------------
("13", "02-hazid-i-hazop.mdx", "F1 minor",
 "IEC 61882 4.1: leader 'preferably assisted by a recorder'",
 "- Zespół (4.1): badanie prowadzi przeszkolony i doświadczony prowadzący, wspierany przez protokolanta i specjalistów z różnych dziedzin.",
 "- Zespół (4.1): badanie prowadzi przeszkolony i doświadczony prowadzący, najlepiej wspierany przez protokolanta; badanie opiera się na specjalistach z różnych dziedzin.", 1),
("14", "02-hazid-i-hazop.mdx", "F1 minor",
 "notes: recorder not required",
 "Norma wymaga prowadzącego, który zna metodę, protokolanta i specjalistów z różnych dziedzin.",
 "Norma przewiduje prowadzącego, który zna metodę, najlepiej z protokolantem, oraz specjalistów z różnych dziedzin.", 1),
("15", "02-hazid-i-hazop.mdx", "F1 minor",
 "TRAS 2.1(14)/1.4(28): 'zusätzliche Gasverbrauchseinrichtung' = flare or gas burner",
 "wymaga, by pochodnia miała pierwszeństwo przed zadziałaniem zabezpieczenia nadciśnieniowego.",
 "wymaga, by dodatkowe urządzenie zużywające gaz (np. pochodnia) miało pierwszeństwo przed zadziałaniem zabezpieczenia nadciśnieniowego.", 1),
("16", "02-hazid-i-hazop.mdx", "F1 minor",
 "same, on 'Od wyników HAZOP do wymagań'",
 "- **Blokada**: automatyczne włączenie pochodni przed wypływem biogazu",
 "- **Blokada**: automatyczne włączenie dodatkowego urządzenia zużywającego gaz (np. pochodni) przed wypływem biogazu", 1),
("17", "02-hazid-i-hazop.mdx", "F1 minor",
 "Uadiale: CWIF statistics compiled from press reports — visible hedge",
 "| turbiny wiatrowe: wyładowania wymieniane jako pierwsza przyczyna zapłonu (Uadiale i in. 2014) |",
 "| turbiny wiatrowe: wyładowania na pierwszym miejscu wśród przyczyn zapłonu w zestawieniu doniesień prasowych (CWIF), wg Uadiale i in. 2014 |", 1),
("18", "02-hazid-i-hazop.mdx", "F1 minor",
 "SVLFG TI 4 limits the air pump but does not require O₂ measurement",
 "kontrola dozowania powietrza (SVLFG TI 4) |",
 "kontrola dozowania powietrza (ocena własna na podstawie SVLFG TI 4) |", 1),
("19", "02-hazid-i-hazop.mdx", "F1 minor",
 "TRAS 2.6.3(3): 'separat von der Gasfüllstandsmessung', not 'independent'",
 "Zwróćcie uwagę na napełnienie: TRAS wymaga osobnych urządzeń dla minimum i maksimum, niezależnych od pomiaru ruchowego.",
 "Zwróćcie uwagę na napełnienie: TRAS wymaga, by urządzenia sygnalizujące minimum i maksimum były wykonane oddzielnie od pomiaru napełnienia, a minimum i maksimum zgłaszał system ochronny.", 1),
("20", "02-hazid-i-hazop.mdx", "F1 minor",
 "Jenkins: plants 'are reported to have exploded'; causes: commissioning practice",
 "Przegląd Jenkinsa i współautorów opisuje co najmniej pięć instalacji, które wybuchły przy pierwszym uruchomieniu.",
 "Według przeglądu Jenkinsa i współautorów co najmniej pięć instalacji miało wybuchnąć przy pierwszym uruchomieniu; autorzy wskazują na niestosowanie zasad rozruchu, m.in. przedmuchu gazem obojętnym i zezwoleń na prace niebezpieczne pożarowo.", 1),
("21", "02-hazid-i-hazop.mdx", "F1 minor (modified wording)",
 "'cecha' is the defined term for characteristic (lesson 17); 'essential features' rendered differently",
 "składnik części, który pozwala określić jej istotne cechy, np. materiał, czynność, urządzenie.",
 "składnik części, który pozwala rozpoznać jej zasadnicze aspekty (ang. essential features), np. materiał, czynność, urządzenie.", 1),
("22", "02-hazid-i-hazop.mdx", "F2 minor (applied to all pages)",
 "TRAS 120 Lesefassung: 'mit Korrektur vom 27. Februar 2019'",
 "zm. 2019", "korekta 2019", 2),
# ---------------- 03 ----------------
("23", "03-fmea-i-fmeca.mdx", "F2 MAJOR (checked by coordinator in the slide's own Table 7 values)",
 "offshore: gearbox, blades, generator also have O = 5; the tower is first because of S = 4",
 "- Wieża jest pierwsza z powodu najwyższej oceny występowania (O = 5), a nie ciężkości: na lądzie wieża ma S = 3, a przekładnia S = 4.",
 "- Na lądzie wieża jest pierwsza dzięki ocenie występowania (O = 5), a nie ciężkości: przekładnia ma S = 4, ale O = 3. Na morzu O = 5 mają też przekładnia, łopaty i generator, a wieżę wyróżnia S = 4.", 1),
("24", "03-fmea-i-fmeca.mdx", "F2 minor",
 "Walgern 2026 ranking per MW: rotor system incl. pitch first, then control; pitch, control, converter called critical",
 "najwięcej awarii na MW rocznie ma układ zmiany kąta łopat, potem sterowanie i przekształtnik.",
 "najwięcej awarii na MW rocznie ma układ wirnika (z układem zmiany kąta łopat), potem sterowanie; za krytyczne autorzy uznają układ zmiany kąta łopat, sterowanie i przekształtnik.", 1),
("25", "03-fmea-i-fmeca.mdx", "F2 minor",
 "notes, same",
 "Nowy zbiór danych z 2026 roku, obejmujący też farmy lądowe, również stawia układ zmiany kąta łopat na pierwszym miejscu.",
 "Nowy zbiór danych z 2026 roku, obejmujący też farmy lądowe, również stawia na pierwszym miejscu układ wirnika z układem zmiany kąta łopat.", 1),
("26", "03-fmea-i-fmeca.mdx", "F2 minor",
 "Carroll: 1,076 is pitch/hydraulics; blades are a separate category",
 "czyli ok. 5,8 razy rzadziej niż układ łopat (obliczenia własne).",
 "czyli ok. 5,8 razy rzadziej niż układ zmiany kąta łopat i hydraulika (obliczenia własne).", 1),
("27", "03-fmea-i-fmeca.mdx", "F2 minor",
 "Colli: result in the Conclusions",
 "(wg streszczenia artykułu)", "(wg wniosków artykułu)", 1),
("28", "03-fmea-i-fmeca.mdx", "F2 minor",
 "IEC 60812 3.1.15: criticality measures 'normally combine'",
 "Krytyczność łączy ciężkość z co najmniej jedną inną cechą rodzaju uszkodzenia.",
 "Miary krytyczności zwykle łączą ciężkość skutku z co najmniej jedną inną cechą rodzaju uszkodzenia (3.1.15).", 1),
("29", "03-fmea-i-fmeca.mdx", "F2 minor",
 "IEC 60812 3.2 lists SOD (severity, occurrence, detectability) and uses them in the RPN method (B.4)",
 "- W praktyce arkusz uzupełnia się o oceny: S — ciężkość (ang. severity), O — występowanie (ang. occurrence) i D — wykrywalność (ang. detection; wyższa ocena oznacza trudniejsze wykrycie). IEC 60812 mówi o ciężkości i prawdopodobieństwie (ang. likelihood) i nie narzuca skal.",
 "- Do szeregowania stosuje się oceny: S — ciężkość (ang. severity), O — występowanie (ang. occurrence) i D — wykrywalność (ang. detectability; wyższa ocena oznacza trudniejsze wykrycie). IEC 60812 używa ich w metodzie RPN (zał. B.4), w definicjach mówi o ciężkości i prawdopodobieństwie (ang. likelihood) i nie narzuca skal.", 1),
("30", "03-fmea-i-fmeca.mdx", "F2 minor",
 "column order is the writer's inference",
 " W typowym arkuszu kolumny układa się w tej kolejności.",
 " W typowym arkuszu kolumny układa się w tej kolejności (ocena własna).", 1),
("31", "03-fmea-i-fmeca.mdx", "F2 minor",
 "notes, same",
 "Kolejność kroków w normie wyznacza układ kolumn arkusza, więc warto ją zapamiętać.",
 "Kolejność kroków w normie dobrze oddaje logikę arkusza, choć układ kolumn bywa różny.", 1),
("32", "03-fmea-i-fmeca.mdx", "F2 minor",
 "Tavner D = 10: 'No known monitoring methods available'",
 "10 wykrycie prawie niemożliwe: brak metody wykrywania",
 "10 wykrycie prawie niemożliwe: brak znanych metod monitorowania", 1),
("33", "03-fmea-i-fmeca.mdx", "F2 minor (safety wording)",
 "only failures not revealed by self-diagnostics are hidden (IEC 60300-3-11 3.1.11)",
 "Niesprawny czujnik gazu milczy, więc monitoring procesu go nie pokaże (ocena własna).",
 "Uszkodzenie czujnika gazu, którego nie wykrywa jego autodiagnostyka, jest ukryte: czujnik milczy, a monitoring procesu tego nie pokaże (ocena własna).", 1),
("34", "03-fmea-i-fmeca.mdx", "F2 minor (safety wording)",
 "notes, same",
 "Jeśli uszkodzenie jest ukryte, jak niesprawny czujnik gazu, monitoring procesu go nie pokaże, bo czujnik po prostu milczy.",
 "Jeśli uszkodzenie jest ukryte, na przykład uszkodzenie czujnika gazu niewykryte przez jego autodiagnostykę, monitoring procesu go nie pokaże, bo czujnik po prostu milczy.", 1),
("35", "03-fmea-i-fmeca.mdx", "F2 minor (modified)",
 "EPRI category is 'Cell/Module' (W1 page 01 says 'ogniwom' — reported in ledger-update)",
 "przypisuje ogniwom 3 z 26 incydentów o ustalonej przyczynie (11%;",
 "przypisuje kategorii ogniwo lub moduł (ang. Cell/Module) 3 z 26 incydentów o ustalonej przyczynie (11%;", 1),
# ---------------- 04 ----------------
("36", "04-fta-eta-i-bow-tie.mdx", "F2 minor",
 "IEC 61025 3.9: 'cannot be further developed'",
 "zdarzenie lub stan, którego nie rozwija się dalej.",
 "zdarzenie lub stan, którego nie można dalej rozwinąć.", 1),
("37", "04-fta-eta-i-bow-tie.mdx", "F2 minor",
 "NUREG-0492 Table IV-1: 'External Event' (house symbol)",
 "zdarzenie „domowe”", "zdarzenie zewnętrzne (symbol domku)", 1),
("38", "04-fta-eta-i-bow-tie.mdx", "F2 minor",
 "Yuan 2026: top-event probability of a fuzzy BN = model-derived risk index for a reference scenario",
 "Ich wynik 28% to prawdopodobieństwo warunkowe z ocen ekspertów, a nie częstość na rok.",
 "Ich wynik 28% to wskaźnik z modelu (rozmyta sieć bayesowska, oceny ekspertów) dla scenariusza odniesienia, a nie częstość na rok.", 1),
("39", "04-fta-eta-i-bow-tie.mdx", "F2 minor",
 "with q = 0,02 the naive gain is 1/q = 50, not 100",
 "Typowe nieporozumienie: druga sztuka tego samego czujnika zawsze poprawia bezpieczeństwo stokrotnie.",
 "Typowe nieporozumienie: druga sztuka tego samego czujnika zawsze poprawia wynik tyle, ile wynika z mnożenia, tu 50-krotnie.", 1),
("40", "04-fta-eta-i-bow-tie.mdx", "F2 minor",
 "CCPS/EI book not read; content checked in Johnson et al. 2018",
 "(CCPS — Center for Chemical Process Safety, i Energy Institute, 2018).",
 "(CCPS — Center for Chemical Process Safety, i Energy Institute, 2018; wg Johnsona i in., 2018).", 1),
("41", "04-fta-eta-i-bow-tie.mdx", "F2 minor",
 "the overpressure device itself releases biogas (TRAS 2.6.3(3)); it is a barrier against rupture",
 "przed zadziałaniem zabezpieczenia podciśnieniowego trzeba ograniczyć, a w razie potrzeby zatrzymać pobór gazu (2.4(8)).\n",
 "przed zadziałaniem zabezpieczenia podciśnieniowego trzeba ograniczyć, a w razie potrzeby zatrzymać pobór gazu (2.4(8)).\n- Zadziałanie zabezpieczenia nadciśnieniowego też uwalnia biogaz, ale w przewidzianym miejscu; barierą jest ono wobec rozerwania zbiornika (ocena własna).\n", 1),
("42", "04-fta-eta-i-bow-tie.mdx", "F2 minor",
 "TRAS 120 Lesefassung: 'Korrektur'",
 "wersja 12/2018 ze zmianą z 27.02.2019", "wersja 12/2018 z korektą z 27.02.2019", 1),
# ---------------- 05 ----------------
("43", "05-lopa-i-sil.mdx", "F3 MAJOR (RR716 §6.5.2 opened by coordinator)",
 "RR716 adds: the whole system incl. alarm and cabling must be considered, the figure appears too low, PFD < 0,1 cannot be claimed; device = float/displacer level device",
 "- Dane rzeczywiste (RR716, pkt 6.5.2): wyłącznik pływakowy, 19,3 × 10⁻⁶ /h, czyli ok. 0,17 /rok; przy teście raz w roku PFD ≈ 0,17/2 ≈ 0,085.",
 "- Dane rzeczywiste (RR716, pkt 6.5.2): pływakowy lub wypornościowy czujnik poziomu w alarmie HH, 19,3 × 10⁻⁶ /h, czyli ok. 0,17 /rok; przy teście raz w roku PFD ≈ 0,17/2 ≈ 0,085. RR716 zaznacza jednak, że czujnika nie wolno oceniać w oderwaniu od całego układu (alarm, okablowanie), więc ta wartość wydaje się zbyt niska, a dla tej warstwy nie można przyjąć PFD mniejszego niż 0,1.", 1),
("44", "05-lopa-i-sil.mdx", "F3 MAJOR (notes)",
 "notes, same",
 "Przykład z raportu HSE jest prawdziwy: wyłącznik pływakowy o intensywności niebezpiecznych uszkodzeń około 0,17 na rok, testowany raz w roku, ma PFD około 0,085.",
 "Przykład z raportu HSE jest prawdziwy: pływakowy czujnik poziomu o intensywności niebezpiecznych uszkodzeń około 0,17 na rok, testowany raz w roku, daje PFD około 0,085. Autorzy dodają jednak, że liczy się cały układ z alarmem i okablowaniem, więc PFD poniżej 0,1 nie wolno przyjąć; to ta sama granica co w W1.", 1),
("45", "05-lopa-i-sil.mdx", "F3 minor (modified)",
 "variant B uses 0,1 although the page shows RR716's 0,19; state the result with 0,19",
 "czyli przedział **SIL 1**. Różnica wynika wyłącznie z organizacji pracy.",
 "czyli przedział **SIL 1**. Różnica wynika wyłącznie z organizacji pracy. Przy PFD warstwy alarmowej 0,19 (RR716, slajd o typowych błędach) byłoby $f = 1{,}9 \\times 10^{-4}$ /rok i $RRF = 38$, nadal SIL 1.", 1),
("46", "05-lopa-i-sil.mdx", "F3 minor",
 "SAFEChE: 'Operator failure 10⁻²/opportunity' — no 'routine'",
 "| Błąd operatora przy czynności rutynowej | IEF |",
 "| Błąd operatora | IEF |", 1),
("47", "05-lopa-i-sil.mdx", "F3 minor",
 "RR716 (companies A, D) refers to the first edition BS EN 61511-3 Table F.3",
 "- RR716: firmy brały prawdopodobieństwa błędu człowieka z tablicy F.3 normy bez uzasadnienia.",
 "- RR716: firmy (m.in. A i D) brały prawdopodobieństwa błędu człowieka z tablicy F.3 pierwszego wydania normy (BS EN 61511-3) bez uzasadnienia.", 1),
("48", "05-lopa-i-sil.mdx", "F3 minor",
 "RR716 footnote: limit applies to a BPCS that places a demand on a protection layer",
 "- Dla BPCS niezgodnego z normą pierwsze wydanie IEC 61511 nie pozwalało",
 "- Dla BPCS niezgodnego z normą, który jest zdarzeniem inicjującym (stawia żądanie warstwie ochrony), pierwsze wydanie IEC 61511 nie pozwalało", 1),
("49", "05-lopa-i-sil.mdx", "F3 minor",
 "King 2014: 'operating as a continuous control function'",
 "**tryb ciągły** — funkcja działa jak ciągła funkcja sterowania.",
 "**tryb ciągły** — funkcja bezpieczeństwa działa jako ciągła funkcja sterowania.", 1),
("50", "05-lopa-i-sil.mdx", "F3 minor",
 "β = 0 is outside the 1–10% range",
 "Umowne wartości z tabeli leżą w zakresie dla czujników.",
 "Niezerowe wartości β z tabeli (0,02–0,10) leżą w zakresie dla czujników; β = 0 to przypadek odniesienia.", 1),
("51", "05-lopa-i-sil.mdx", "F3 minor",
 "IFA report based on the 2015 edition; DGUV = umbrella association of statutory accident insurance",
 "(IFA, instytut bezpieczeństwa pracy niemieckiego ubezpieczyciela DGUV, opisuje ją jako graf ryzyka)",
 "(IFA, instytut niemieckiego ustawowego ubezpieczenia wypadkowego DGUV, opisuje tę metodę dla wydania z 2015 r. jako graf ryzyka)", 1),
("52", "05-lopa-i-sil.mdx", "F3 minor",
 "ISO 13849-1 wording: probability of dangerous failure per hour",
 "Miarą jest więc częstość niebezpiecznych uszkodzeń na godzinę, a nie PFDavg.",
 "Miarą jest więc średnie prawdopodobieństwo niebezpiecznego uszkodzenia na godzinę (w terminologii ISO 13849-1), a nie PFDavg.", 1),
("53", "05-lopa-i-sil.mdx", "F3 minor",
 "W1 part 5 qualifier: BPCS not designed to IEC 61511",
 "BPCS (Basic Process Control System — podstawowy system sterowania procesem) dostaje najwyżej RRF 10",
 "BPCS (Basic Process Control System — podstawowy system sterowania procesem) niezaprojektowany według IEC 61511 dostaje najwyżej RRF 10", 1),
("54", "05-lopa-i-sil.mdx", "F1 minor (consequence on 05)",
 "Stanley: 10⁻⁵ middle of ALARP region, 10⁻⁶ for firms aiming at the broadly acceptable line",
 "Mieści się między celami dla pojedynczego scenariusza LOPA, które Stanley i in. (2018) wyprowadzają z granic R2P2: 10⁻⁵ /rok i 10⁻⁶ /rok",
 "Mieści się między celami dla pojedynczego scenariusza LOPA, które omawiają Stanley i in. (2018): 10⁻⁵ /rok (środek obszaru ALARP) i 10⁻⁶ /rok", 1),
("55", "05-lopa-i-sil.mdx", "F2 minor (applied to all pages)",
 "TRAS 120: 'Korrektur'",
 "2018, zm. 2019", "2018, korekta 2019", 1),
# ---------------- 06 ----------------
("56", "06-podsumowanie.mdx", "F3 minor",
 "HAZOP row duplicated the LOPA question; align with 01",
 "| HAZOP | Jakie odchylenia od zamierzenia projektowego są możliwe i czy zabezpieczenia wystarczą? |",
 "| HAZOP | Jakie odchylenia od zamierzenia projektowego są możliwe i co je zatrzyma? |", 1),
("57", "06-podsumowanie.mdx", "F3 minor (modified)",
 "Dunn & Sands: rationalization documents consequence, response time and operator action",
 "- **Lista alarmów i racjonalizacja**: każdy alarm z HAZOP lub LOPA musi mieć przyczynę, oczekiwaną reakcję operatora i czas na nią (definicja alarmu:",
 "- **Lista alarmów i racjonalizacja**: dla każdego alarmu z HAZOP lub LOPA dokumentuje się skutek braku reakcji, działanie operatora i czas na reakcję (za Dunnem i Sandsem, 2020; definicja alarmu:", 1),
("58", "06-podsumowanie.mdx", "F3 minor",
 "four quiz questions need calculation (Q5, Q6, Q8, Q9)",
 "w tym trzema obliczeniowymi", "w tym czterema wymagającymi obliczeń", 1),
("59", "06-podsumowanie.mdx", "F1 minor (consequence in the quiz)",
 "quiz Q2 explanation aligned with fix 5",
 "Ani Kodeks pracy, ani rozporządzenie w sprawie ogólnych przepisów BHP nie wskazują metody oceny ani liczbowych kryteriów ryzyka.",
 "Ani Kodeks pracy, ani rozporządzenie w sprawie ogólnych przepisów BHP nie wskazują metody oceny; art. 226 i § 39a nie podają też liczbowych kryteriów ryzyka.", 1),
("60", "06-podsumowanie.mdx", "F2 minor (applied to all pages)",
 "TRAS 120: 'Korrektur'",
 "(2018, zm. 2019)", "(2018, korekta 2019)", 1),
# ---------------- index ----------------
("61", "index.md", "F3 minor",
 "IEC 31010:2019 Annex B contains neither HAZID nor SIL",
 "Omawiamy proces zarządzania ryzykiem według ISO 31000:2018 i metody opisane w IEC 31010:2019: HAZID (Hazard Identification — identyfikacja zagrożeń), HAZOP (Hazard and Operability Study — badanie zagrożeń i zdolności do działania), FMEA (Failure Modes and Effects Analysis — analiza rodzajów i skutków uszkodzeń) i FMECA (Failure Modes, Effects and Criticality Analysis — analiza rodzajów, skutków i krytyczności uszkodzeń), FTA (Fault Tree Analysis — analiza drzewa niezdatności), ETA (Event Tree Analysis — analiza drzewa zdarzeń), bow-tie, LOPA (Layer of Protection Analysis — analiza warstw ochrony) oraz dobór SIL (Safety Integrity Level — poziom nienaruszalności bezpieczeństwa).",
 "Omawiamy proces zarządzania ryzykiem według ISO 31000:2018, metody opisane w IEC 31010:2019 — HAZOP (Hazard and Operability Study — badanie zagrożeń i zdolności do działania), FMEA (Failure Modes and Effects Analysis — analiza rodzajów i skutków uszkodzeń) i FMECA (Failure Modes, Effects and Criticality Analysis — analiza rodzajów, skutków i krytyczności uszkodzeń), FTA (Fault Tree Analysis — analiza drzewa niezdatności), ETA (Event Tree Analysis — analiza drzewa zdarzeń), bow-tie i LOPA (Layer of Protection Analysis — analiza warstw ochrony) — a także HAZID (Hazard Identification — identyfikacja zagrożeń; ISO 17776) i dobór SIL (Safety Integrity Level — poziom nienaruszalności bezpieczeństwa; IEC 61508, IEC 61511).", 1),
("62", "index.md", "coordinator",
 "W9 line: redundant parenthesis; forward reference kept in substance",
 "  - W9: Biogazownie — ochrona przeciwwybuchowa, detekcja gazów i bezpieczeństwo procesowe (W9 — bezpieczeństwo procesowe biogazowni) — przykłady HAZOP, bow-tie i LOPA zbiornika biogazu wrócą tam razem z doborem detektorów i nastaw;",
 "  - W9: Biogazownie — ochrona przeciwwybuchowa, detekcja gazów i bezpieczeństwo procesowe — przykłady HAZOP, bow-tie i LOPA zbiornika biogazu wrócą tam jako punkt wyjścia do bezpieczeństwa procesowego biogazowni, razem z doborem detektorów i nastaw;", 1),
]

# Rejected findings (not applied), with reasons — listed in fixes.md.
REJECTED = [
]
